import Fuse from 'fuse.js';

const INGREDIENTS_LIST = [
  'chicken breast', 'chicken thighs', 'chicken wings', 'ground chicken', 'whole chicken', 'chicken drumsticks',
  'turkey breast', 'ground turkey', 'turkey thighs', 'duck breast', 'duck legs', 'goose',
  'beef steak', 'ground beef', 'beef roast', 'beef ribs', 'beef brisket', 'beef chuck', 'beef sirloin', 'beef tenderloin', 'beef short ribs', 'beef shank',
  'pork chops', 'pork tenderloin', 'ground pork', 'pork shoulder', 'pork ribs', 'pork belly',
  'bacon', 'pancetta', 'prosciutto', 'ham', 'sausage', 'chorizo', 'italian sausage', 'bratwurst', 'kielbasa',
  'lamb chops', 'ground lamb', 'lamb shoulder', 'leg of lamb', 'lamb shank',
  'salmon', 'tuna', 'cod', 'halibut', 'trout', 'mackerel', 'sardines', 'anchovies', 'tilapia', 'sea bass', 'snapper', 'mahi mahi', 'swordfish', 'monkfish',
  'shrimp', 'prawns', 'crab', 'lobster', 'scallops', 'mussels', 'clams', 'oysters', 'squid', 'octopus', 'crayfish',
  'eggs', 'duck eggs', 'quail eggs',
  'tofu', 'tempeh', 'seitan', 'textured vegetable protein',
  'chickpeas', 'black beans', 'kidney beans', 'pinto beans', 'navy beans', 'lentils', 'split peas', 'black-eyed peas', 'cannellini beans', 'edamame', 'fava beans', 'lima beans',
  'rice', 'brown rice', 'wild rice', 'jasmine rice', 'basmati rice', 'arborio rice', 'sushi rice', 'sticky rice', 'black rice', 'red rice',
  'quinoa', 'barley', 'farro', 'bulgur', 'couscous', 'millet', 'amaranth', 'teff', 'freekeh', 'wheat berries',
  'pasta', 'spaghetti', 'penne', 'fettuccine', 'linguine', 'rigatoni', 'macaroni', 'lasagna noodles', 'ravioli', 'gnocchi', 'ramen noodles', 'soba noodles', 'rice noodles', 'udon noodles', 'bucatini', 'orecchiette', 'fusilli', 'rotini',
  'bread', 'sourdough bread', 'whole wheat bread', 'rye bread', 'baguette', 'ciabatta', 'focaccia', 'pita bread', 'naan', 'tortillas', 'flour tortillas', 'corn tortillas', 'english muffins', 'bagels', 'breadcrumbs', 'panko', 'croutons',
  'potatoes', 'sweet potatoes', 'yams',
  'onions', 'shallots', 'green onions', 'scallions', 'leeks', 'chives',
  'garlic', 'ginger', 'galangal', 'turmeric root',
  'tomatoes', 'tomato paste', 'tomato sauce', 'crushed tomatoes', 'diced tomatoes', 'sun-dried tomatoes',
  'bell peppers', 'jalapeños', 'serrano peppers', 'poblano peppers', 'anaheim peppers', 'habanero peppers', 'chipotle peppers', 'cayenne peppers',
  'broccoli', 'broccoli rabe', 'cauliflower', 'brussels sprouts', 'cabbage', 'napa cabbage', 'bok choy',
  'spinach', 'kale', 'arugula', 'watercress', 'mizuna', 'tatsoi',
  'lettuce', 'romaine', 'iceberg lettuce',
  'mushrooms', 'shiitake', 'oyster mushrooms', 'enoki', 'maitake', 'morels', 'chanterelles',
  'carrots', 'celery', 'celery root', 'cucumber',
  'zucchini', 'yellow squash', 'pattypan squash', 'eggplant',
  'asparagus', 'green beans', 'snap peas', 'snow peas',
  'corn', 'peas', 'artichokes', 'artichoke hearts',
  'avocado', 'radishes', 'daikon', 'turnips', 'rutabaga', 'parsnips', 'beets',
  'fennel', 'butternut squash', 'acorn squash', 'spaghetti squash', 'delicata squash', 'kabocha squash', 'pumpkin',
  'okra', 'collard greens', 'mustard greens', 'swiss chard', 'endive', 'radicchio', 'escarole',
  'cheese', 'cheddar', 'mozzarella', 'parmesan', 'pecorino romano', 'feta', 'goat cheese', 'ricotta', 'cottage cheese', 'cream cheese', 'swiss cheese', 'gouda', 'brie', 'camembert', 'blue cheese', 'gorgonzola', 'manchego', 'gruyère', 'fontina', 'provolone', 'monterey jack', 'pepper jack', 'havarti', 'mascarpone', 'burrata',
  'butter', 'unsalted butter', 'salted butter', 'ghee', 'margarine',
  'olive oil', 'extra virgin olive oil', 'vegetable oil', 'canola oil', 'avocado oil', 'coconut oil', 'sesame oil', 'peanut oil', 'sunflower oil', 'grapeseed oil', 'walnut oil',
  'milk', 'whole milk', 'skim milk', 'almond milk', 'soy milk', 'oat milk', 'coconut milk', 'rice milk', 'hemp milk', 'cashew milk',
  'heavy cream', 'light cream', 'half and half', 'sour cream', 'crème fraîche',
  'greek yogurt', 'plain yogurt', 'buttermilk', 'kefir',
  'lemon', 'lime', 'orange', 'grapefruit', 'blood orange', 'mandarin', 'clementine', 'tangerine', 'lemon zest', 'lime zest', 'orange zest',
  'basil', 'cilantro', 'parsley', 'dill', 'rosemary', 'thyme', 'oregano', 'sage', 'mint', 'tarragon', 'marjoram', 'bay leaves', 'curry leaves', 'lemongrass', 'thai basil',
  'salt', 'kosher salt', 'sea salt', 'black pepper', 'white pepper', 'cayenne pepper', 'red pepper flakes', 'paprika', 'smoked paprika',
  'cumin', 'coriander', 'turmeric', 'cinnamon', 'nutmeg', 'allspice', 'cloves', 'cardamom', 'star anise', 'fennel seeds', 'mustard seeds', 'caraway seeds', 'poppy seeds', 'sesame seeds', 'chia seeds', 'flax seeds', 'sunflower seeds', 'pumpkin seeds', 'hemp seeds',
  'almonds', 'walnuts', 'pecans', 'cashews', 'pistachios', 'hazelnuts', 'macadamia nuts', 'pine nuts', 'brazil nuts', 'peanuts', 'peanut butter', 'almond butter', 'cashew butter', 'tahini',
  'honey', 'maple syrup', 'agave', 'brown sugar', 'white sugar', 'powdered sugar', 'coconut sugar', 'turbinado sugar', 'molasses', 'vanilla extract', 'almond extract', 'vanilla bean',
  'vinegar', 'balsamic vinegar', 'red wine vinegar', 'white wine vinegar', 'apple cider vinegar', 'rice vinegar', 'champagne vinegar', 'sherry vinegar', 'malt vinegar',
  'soy sauce', 'tamari', 'worcestershire sauce', 'hot sauce', 'sriracha', 'fish sauce', 'oyster sauce', 'hoisin sauce', 'teriyaki sauce', 'bbq sauce', 'ketchup', 'mustard', 'dijon mustard', 'whole grain mustard', 'mayonnaise', 'aioli', 'salsa', 'pesto', 'hummus', 'tzatziki',
  'capers', 'olives', 'kalamata olives', 'roasted red peppers', 'hearts of palm',
  'coconut', 'shredded coconut', 'coconut flakes', 'coconut cream', 'coconut water', 'coconut flour', 'coconut aminos',
  'raisins', 'dates', 'prunes', 'dried apricots', 'dried cranberries', 'dried cherries', 'dried figs', 'dried mango', 'dried pineapple',
  'bananas', 'plantains', 'apples', 'pears', 'peaches', 'nectarines', 'plums', 'apricots',
  'strawberries', 'blueberries', 'raspberries', 'blackberries', 'cranberries', 'gooseberries', 'currants', 'grapes',
  'pineapple', 'mango', 'papaya', 'kiwi', 'passion fruit', 'pomegranate', 'dragon fruit', 'lychee', 'rambutan', 'watermelon', 'cantaloupe', 'honeydew',
  'chicken broth', 'chicken stock', 'beef broth', 'beef stock', 'vegetable broth', 'vegetable stock', 'bone broth', 'fish stock', 'clam juice',
  'white wine', 'red wine', 'sherry', 'marsala', 'vermouth', 'beer', 'stout', 'ale',
  'flour', 'all-purpose flour', 'whole wheat flour', 'bread flour', 'cake flour', 'pastry flour', 'almond flour', 'rice flour', 'cornmeal', 'polenta', 'cornstarch', 'arrowroot', 'tapioca starch',
  'baking powder', 'baking soda', 'yeast', 'active dry yeast', 'instant yeast', 'cream of tartar',
  'chocolate', 'dark chocolate', 'milk chocolate', 'white chocolate', 'cocoa powder', 'chocolate chips', 'cacao nibs',
  'vanilla paste', 'lemon extract', 'orange extract',
  'brown rice syrup', 'golden syrup',
  'sumac', 'za\'atar', 'harissa', 'gochujang', 'miso', 'mirin', 'sake', 'rice wine',
  'cannellini', 'white beans', 'adzuki beans', 'mung beans',
  'vermicelli', 'rice paper', 'wonton wrappers', 'phyllo dough', 'pie crust',
  'sweet corn', 'hominy', 'grits',
  'water chestnuts', 'bamboo shoots', 'bean sprouts', 'nori', 'wakame', 'kombu',
  'lime leaves', 'kaffir lime', 'bird\'s eye chili', 'scotch bonnet',
  'apple', 'pear', 'fig', 'persimmon', 'quince', 'rhubarb', 'elderberries', 'blackcurrants', 'redcurrants',
  'jackfruit', 'breadfruit', 'star fruit', 'guava', 'tamarind', 'date paste',
  'nutmeg', 'mace', 'saffron', 'sumac', 'smoked salt', 'liquid smoke',
  'gelatin', 'agar agar', 'pectin', 'xanthan gum',
  'cocoa butter', 'nutella', 'marshmallows', 'maraschino cherries',
  'anchovy paste', 'harissa', 'sambal oelek', 'gochugaru',
];

export const INGREDIENTS = [...new Set(INGREDIENTS_LIST)].sort();

const fuse = new Fuse(INGREDIENTS, {
  threshold: 0.4,
  ignoreLocation: true,
});

export function searchIngredients(query: string, limit: number = 10): string[] {
  if (!query.trim()) return [];
  return fuse.search(query).slice(0, limit).map((r) => r.item);
}
