const INGREDIENTS_LIST = [
  'chicken breast', 'chicken thighs', 'chicken wings', 'ground chicken', 'whole chicken', 'chicken drumsticks',
  'turkey breast', 'ground turkey', 'turkey thighs', 'duck breast', 'duck legs', 'goose',
  'beef steak', 'ground beef', 'beef roast', 'beef ribs', 'beef brisket', 'beef chuck', 'beef sirloin', 'beef tenderloin', 'beef short ribs', 'beef shank',
  'pork chops', 'pork tenderloin', 'ground pork', 'pork shoulder', 'pork ribs', 'pork belly',
  'bacon', 'pancetta', 'prosciutto', 'ham', 'sausage', 'chorizo', 'italian sausage', 'bratwurst', 'kielbasa',
  'lamb chops', 'ground lamb', 'lamb shoulder', 'leg of lamb', 'lamb shank',
  'salmon', 'tuna', 'cod', 'halibut', 'trout', 'mackerel', 'sardines', 'anchovies', 'tilapia', 'sea bass', 'snapper', 'mahi mahi', 'swordfish', 'monkfish',
  'shrimp', 'prawns', 'crab', 'lobster', 'scallops', 'mussels', 'clams', 'oysters', 'squid', 'octopus', 'crayfish',
  'eggs', 'duck eggs', 'quail eggs',
  'tofu', 'tempeh', 'seitan', 'textured vegetable protein',
  'chickpeas', 'black beans', 'kidney beans', 'pinto beans', 'navy beans', 'lentils', 'red lentils', 'green lentils', 'black lentils', 'split peas', 'black-eyed peas', 'cannellini beans', 'edamame', 'fava beans', 'lima beans', 'garbanzo beans',
  'rice', 'brown rice', 'wild rice', 'jasmine rice', 'basmati rice', 'arborio rice', 'sushi rice', 'sticky rice',
  'quinoa', 'barley', 'farro', 'bulgur', 'couscous', 'millet', 'amaranth', 'teff', 'freekeh',
  'pasta', 'spaghetti', 'penne', 'fettuccine', 'linguine', 'rigatoni', 'macaroni', 'lasagna noodles', 'ravioli', 'gnocchi', 'ramen noodles', 'soba noodles', 'rice noodles', 'udon noodles', 'angel hair pasta', 'bucatini', 'orecchiette',
  'bread', 'sourdough bread', 'whole wheat bread', 'rye bread', 'baguette', 'ciabatta', 'focaccia', 'pita bread', 'naan', 'tortillas', 'flour tortillas', 'corn tortillas', 'english muffins', 'bagels',
  'potatoes', 'sweet potatoes', 'yams', 'russet potatoes', 'red potatoes', 'white potatoes', 'fingerling potatoes', 'new potatoes', 'purple potatoes',
  'onions', 'yellow onions', 'red onions', 'white onions', 'shallots', 'green onions', 'scallions', 'leeks', 'chives',
  'garlic', 'ginger', 'galangal', 'turmeric root',
  'tomatoes', 'cherry tomatoes', 'grape tomatoes', 'roma tomatoes', 'beefsteak tomatoes', 'heirloom tomatoes', 'tomato paste', 'tomato sauce', 'crushed tomatoes', 'diced tomatoes', 'sun-dried tomatoes',
  'bell peppers', 'red bell peppers', 'green bell peppers', 'yellow bell peppers', 'orange bell peppers', 'jalapeños', 'serrano peppers', 'poblano peppers', 'anaheim peppers', 'habanero peppers', 'chipotle peppers', 'cayenne peppers',
  'broccoli', 'broccoli rabe', 'cauliflower', 'brussels sprouts', 'cabbage', 'red cabbage', 'napa cabbage', 'savoy cabbage', 'bok choy', 'baby bok choy',
  'spinach', 'baby spinach', 'kale', 'curly kale', 'lacinato kale', 'arugula', 'watercress', 'mizuna', 'tatsoi',
  'lettuce', 'romaine lettuce', 'iceberg lettuce', 'butter lettuce', 'red leaf lettuce', 'green leaf lettuce', 'bibb lettuce',
  'mushrooms', 'button mushrooms', 'cremini mushrooms', 'portobello mushrooms', 'shiitake mushrooms', 'oyster mushrooms', 'enoki mushrooms', 'maitake mushrooms', 'morel mushrooms', 'chanterelle mushrooms',
  'carrots', 'baby carrots', 'celery', 'celery root', 'cucumber', 'english cucumber', 'persian cucumber',
  'zucchini', 'yellow squash', 'pattypan squash', 'eggplant', 'japanese eggplant', 'thai eggplant',
  'asparagus', 'green beans', 'haricot verts', 'snap peas', 'snow peas', 'fava beans', 'lima beans',
  'corn', 'corn on the cob', 'peas', 'sugar snap peas', 'artichokes', 'baby artichokes', 'artichoke hearts',
  'avocado', 'radishes', 'daikon radish', 'turnips', 'rutabaga', 'parsnips', 'beets', 'golden beets', 'chioggia beets',
  'fennel', 'butternut squash', 'acorn squash', 'spaghetti squash', 'delicata squash', 'kabocha squash', 'pumpkin', 'sugar pumpkin',
  'okra', 'collard greens', 'mustard greens', 'swiss chard', 'rainbow chard', 'endive', 'belgian endive', 'radicchio', 'escarole',
  'cheese', 'cheddar cheese', 'sharp cheddar', 'mild cheddar', 'mozzarella cheese', 'fresh mozzarella', 'parmesan cheese', 'parmigiano reggiano', 'pecorino romano', 'feta cheese', 'goat cheese', 'ricotta cheese', 'cottage cheese', 'cream cheese', 'swiss cheese', 'gouda cheese', 'brie cheese', 'camembert', 'blue cheese', 'gorgonzola', 'stilton', 'manchego', 'gruyère', 'fontina', 'provolone', 'monterey jack', 'pepper jack', 'colby', 'havarti', 'mascarpone', 'burrata',
  'butter', 'unsalted butter', 'salted butter', 'ghee', 'clarified butter', 'margarine',
  'olive oil', 'extra virgin olive oil', 'vegetable oil', 'canola oil', 'avocado oil', 'coconut oil', 'sesame oil', 'peanut oil', 'sunflower oil', 'grapeseed oil', 'walnut oil', 'hazelnut oil', 'pumpkin seed oil',
  'milk', 'whole milk', 'skim milk', '2% milk', '1% milk', 'almond milk', 'soy milk', 'oat milk', 'coconut milk', 'rice milk', 'hemp milk', 'cashew milk',
  'heavy cream', 'light cream', 'half and half', 'whipping cream', 'sour cream', 'crème fraîche',
  'greek yogurt', 'plain yogurt', 'vanilla yogurt', 'buttermilk', 'kefir',
  'lemon', 'lime', 'orange', 'grapefruit', 'blood orange', 'mandarin', 'clementine', 'tangerine', 'lemon zest', 'lime zest', 'orange zest',
  'basil', 'cilantro', 'parsley', 'flat-leaf parsley', 'curly parsley', 'dill', 'rosemary', 'thyme', 'oregano', 'sage', 'mint', 'spearmint', 'peppermint', 'chives', 'tarragon', 'marjoram', 'bay leaves', 'curry leaves', 'lemongrass', 'thai basil', 'holy basil',
  'salt', 'kosher salt', 'sea salt', 'himalayan salt', 'black pepper', 'white pepper', 'pink peppercorns', 'cayenne pepper', 'red pepper flakes', 'crushed red pepper', 'paprika', 'smoked paprika', 'hungarian paprika',
  'cumin', 'coriander', 'turmeric', 'cinnamon', 'nutmeg', 'allspice', 'cloves', 'cardamom', 'green cardamom', 'black cardamom', 'star anise', 'fennel seeds', 'mustard seeds', 'yellow mustard seeds', 'brown mustard seeds', 'caraway seeds', 'poppy seeds', 'sesame seeds', 'black sesame seeds', 'chia seeds', 'flax seeds', 'sunflower seeds', 'pumpkin seeds', 'hemp seeds',
  'almonds', 'walnuts', 'pecans', 'cashews', 'pistachios', 'hazelnuts', 'macadamia nuts', 'pine nuts', 'brazil nuts', 'peanuts', 'peanut butter', 'almond butter', 'cashew butter', 'tahini', 'sesame paste',
  'honey', 'maple syrup', 'agave', 'brown sugar', 'white sugar', 'powdered sugar', 'coconut sugar', 'turbinado sugar', 'molasses', 'blackstrap molasses', 'vanilla extract', 'almond extract', 'vanilla bean',
  'vinegar', 'balsamic vinegar', 'red wine vinegar', 'white wine vinegar', 'apple cider vinegar', 'rice vinegar', 'champagne vinegar', 'sherry vinegar', 'malt vinegar',
  'soy sauce', 'tamari', 'worcestershire sauce', 'hot sauce', 'sriracha', 'tabasco', 'fish sauce', 'oyster sauce', 'hoisin sauce', 'teriyaki sauce', 'bbq sauce', 'ketchup', 'mustard', 'dijon mustard', 'whole grain mustard', 'yellow mustard', 'mayonnaise', 'aioli', 'salsa', 'pico de gallo', 'pesto', 'hummus', 'tzatziki',
  'capers', 'olives', 'black olives', 'green olives', 'kalamata olives', 'nicoise olives', 'castelvetrano olives', 'roasted red peppers', 'artichoke hearts', 'hearts of palm', 'sun-dried tomatoes',
  'coconut', 'shredded coconut', 'coconut flakes', 'coconut milk', 'coconut cream', 'coconut water', 'coconut oil', 'coconut butter', 'coconut flour', 'coconut sugar', 'coconut aminos',
  'raisins', 'golden raisins', 'dates', 'medjool dates', 'prunes', 'dried apricots', 'dried cranberries', 'dried cherries', 'dried figs', 'dried mango', 'dried pineapple',
  'bananas', 'plantains', 'apples', 'granny smith apples', 'gala apples', 'fuji apples', 'honeycrisp apples', 'pears', 'bartlett pears', 'anjou pears', 'peaches', 'nectarines', 'plums', 'apricots',
  'berries', 'strawberries', 'blueberries', 'raspberries', 'blackberries', 'cranberries', 'gooseberries', 'currants', 'grapes', 'red grapes', 'green grapes', 'concord grapes',
  'pineapple', 'mango', 'papaya', 'kiwi', 'passion fruit', 'pomegranate', 'dragon fruit', 'lychee', 'rambutan', 'watermelon', 'cantaloupe', 'honeydew', 'cactus pear',
  'chicken broth', 'chicken stock', 'beef broth', 'beef stock', 'vegetable broth', 'vegetable stock', 'bone broth', 'turkey broth', 'fish stock', 'clam juice',
  'wine', 'white wine', 'red wine', 'sherry', 'marsala', 'vermouth', 'beer', 'stout', 'ale',
  'flour', 'all-purpose flour', 'whole wheat flour', 'bread flour', 'cake flour', 'pastry flour', 'almond flour', 'coconut flour', 'rice flour', 'cornmeal', 'polenta', 'cornstarch', 'arrowroot', 'tapioca starch',
  'baking powder', 'baking soda', 'yeast', 'active dry yeast', 'instant yeast', 'cream of tartar',
  'chocolate', 'dark chocolate', 'milk chocolate', 'white chocolate', 'cocoa powder', 'chocolate chips', 'chocolate chunks', 'cacao nibs',
  'vanilla bean', 'vanilla paste', 'almond extract', 'lemon extract', 'orange extract',
  'coconut milk', 'coconut cream', 'coconut water', 'coconut oil', 'coconut butter', 'coconut flour', 'coconut sugar', 'coconut flakes', 'shredded coconut', 'coconut chips', 'coconut aminos',
  'tahini', 'peanut butter', 'almond butter', 'cashew butter', 'sunflower seed butter',
  'honey', 'maple syrup', 'agave nectar', 'brown rice syrup', 'golden syrup',
  'rice', 'brown rice', 'wild rice', 'jasmine rice', 'basmati rice', 'arborio rice', 'sushi rice', 'sticky rice', 'black rice', 'red rice',
  'quinoa', 'red quinoa', 'black quinoa', 'barley', 'pearl barley', 'farro', 'bulgur', 'couscous', 'millet', 'amaranth', 'teff', 'freekeh', 'wheat berries',
  'pasta', 'spaghetti', 'penne', 'fettuccine', 'linguine', 'rigatoni', 'macaroni', 'lasagna noodles', 'ravioli', 'gnocchi', 'ramen noodles', 'soba noodles', 'rice noodles', 'udon noodles', 'angel hair pasta', 'bucatini', 'orecchiette', 'fusilli', 'rotini',
  'breadcrumbs', 'panko breadcrumbs', 'croutons',
  'nuts', 'almonds', 'walnuts', 'pecans', 'cashews', 'pistachios', 'hazelnuts', 'macadamia nuts', 'pine nuts', 'brazil nuts', 'peanuts',
  'seeds', 'sesame seeds', 'black sesame seeds', 'chia seeds', 'flax seeds', 'sunflower seeds', 'pumpkin seeds', 'hemp seeds', 'poppy seeds',
];

export const INGREDIENTS = [...new Set(INGREDIENTS_LIST)].sort();

export function searchIngredients(query: string, limit: number = 10): string[] {
  if (!query.trim()) return [];
  const lowerQuery = query.toLowerCase();
  return INGREDIENTS
    .filter(ing => ing.toLowerCase().includes(lowerQuery))
    .slice(0, limit);
}
